### ISSUE TITLE
M20 - Medium FOV - (Unsupported format)

### ISSUE THREAD

**Issue by mjgruta** [yanburman/sjcam_raw2dng#2]
Hi,

First off all, fantastic work!

I tried to convert the raw file with Medium Field of View settings but it gives me this error message "Unsupported format".

Hope you can support other FOV.
Just message me if you need more info.

Thanks.

**Comment by yanburman** [comment]
One of the FOV crops for SJ5000x is difficult to figure out, since it seems to contain extra pixels that are being discarded by the camera's firmware. I tried to figure the math behind it, but had no success. Shooting raw with crop/zoom has no real benefit anyway, since you don't get any benefit compared to shooting full resolution and cropping in post. If you mean M20 FOV crops, I can give it a try if you provide me the samples.

**Comment by yanburman** [comment]
If you don't provide me the samples to try, I'm going to close this issue for inactivity

**Comment by Bezbod** [comment]
Hi Yan,

Here is the archive with JPG and RAW photos taken from the same point with 3 different angles (normal-middle-narrow): http://dropmefiles.com/6Fvio
And here is the archive with photos taken with narrow angle: http://dropmefiles.com/mEqE4

I would higly appreciate if you could make RAW-files taken with narrow angle usable. But it is OK if it is not possible.

Anyway thanks a lot for your efforts!

**Comment by yanburman** [comment]
It seems that both middle and narrow crop resolutions are messed up. So far I was unable to find proper resolution since it seems to have some extra pixels either in the beginning and /or the end. I will give it another shot, but I wouldn't get your hopes too high.  Sorry. It is not trivial due to bugs in SJCAM firmware

**Comment by Bezbod** [comment]
Well, no problem if you cann't do that. It's completely my fault that I forgot to switch off narrow angle. 
Anyway thanks so much for your efforts and for your convertor! It is just amazing!

**Comment by yanburman** [comment]
Fixed in latest development code. to be part of 1.2.0 release
