### ISSUE TITLE
OSX, no idea what to do with your program ...

### ISSUE THREAD

**Issue by jh96** [yanburman/sjcam_raw2dng#3]
The issue is me, not with your program :)

I have a new M20 and the only reason I bought it was the RAW functionality - I can't believe SJCAM have put out cameras without any compatibility and no one's made a big deal out of it in any reviews.

M problem is that I can't get this software to run. I don't know where to put it or how to get it to work. I can't get a GUI or make it run as a CLI no matter what I do, I can't make anything happen under Lion or the latest OS.
Dragging folders onto the sjcam,_raw2dng file, dragging individual .RAW files onto it, dragging the scam,_raw2dn into the terminal window and hitting return gives me a "permission denied"

Can you tell me exactly what I should be doing?

**Comment by yanburman** [comment]
Have you tried this ?:
https://support.apple.com/en-il/HT202491
I don't have a mac and from what I saw developing for it is a pain.
The GUI should work, but is not packaged with the binary, since installing pre-requisites for the GUI are a pain (on mac).
I believe that if you unblock the binary as seen in the bottom portion of the link I posted, you will be able to run the CLI version and perhaps drag-n-drop folders into it as well.

Let me know if this helps.

**Comment by jh96** [comment]
No, gatekeeper's not the problem.

I get that the wxPython installation is a pain to get the GUI working but this is a work machine and not something I want to spend days testing things out on - I just need to get one method that works.

I suppose I need to know how to run your binary - Someone in the SJCAM forum said it was tested under OSX 10.11 but I have no idea what they did to run it. Do you know?

I ran the Win32 version in a 32bit x86 XP as a VMware installation under OS X 10.7 and that brought up the GUI - I added sources and destinations for the RAW and Jpeg folder, and it reported that the raw2dng [Error193] isn't a valid Win32 application.

**Comment by jh96** [comment]
This has nothing to do with you, but the SJCAM app doesn't work well on my iPad either - The app doesn't rotate when the iPad is rotated, so for my working set-up it's always upside down.
I don't want any of the social media stuff from an app, all the work I do is post production, I just want to transfer the files to a working environment.
In iOS, the connection is made, the wifi pairs, the software can access the camera roll, but nothing on the camera comes up.
In OSX connected by USB the camera contents aren't recognised by the standard image program, instead, the camera is mounted like an External HD and I have to access the contents manually.
I can remove the card, place it in a card reader and it's read as normal.

**Comment by yanburman** [comment]
Hi, regarding the sjcam app, I am not in any way affiliated with sjcam, and have nothing to do with the sjcam zone app. I agree that it is a bloat ware that is poorly written. Regarding running the cli version, I was able to run it on the mac after I compiled it there. Since I don't have a mac and I don't have any experience with developing for mac, I am of little help regarding this issue. The windows binaries work both the 32 and 64 bit cli and GUI, so I have no idea why it is not working for you, except that perhaps it was somehow a 64 bit version binary that would not run on 32 bit windows. I assume that you changed the permissions of the cli binary on mac to include executable permissions. On Linux this would be something like chmod a+x sjcam... from the shell

**Comment by jh96** [comment]
Hi Yan

Yeah, I get that you’re not involved with SJCAM - their Mac software is just bad.
I suspect that the camera is going to be disappointing unless you want 1080/60 footage and have a laptop around to transfer the files manually!
All these bells and whistles and interpolated 4k are just marketing - If you can’t get the simple functions like RAW files and transfers to perform correctly, it's pointless.
Can’t remotely control the camera from any Mac, but there’s youtube videos with android phones doing it fine.

I checked if I had the right binaries and I did indeed have the 32bit and XP is also 32bit and the machine is an x86 … [Error193] isn't a valid Win32 application, is a strange error to get, so I tried the 64bit version afterwards, and that wouldn’t work at all.
I suspect you may be right about the permissions so I went back to the work Mac, currently they are -rw-r--r--  I used chmod 755 sjcam_raw2dng that gave me -rwxr-xr-x

Permissions? Never crossed my mind even though it was printing Permission Denied, duh. So now it's running as a CLI on OS X10.11 - Yippee.

I do have a small amount of knowledge, just enough to be dangerous, but not enough to solve anything without help.
Which brings me to my next problem. Can give me an example of the syntax for creating a DNG file without any changes? Say photo_01.RAW to photo_01.DNG from and to the same folder. Let's call that folder "M20_Photos" ... I can work out the full paths later :)

**Comment by yanburman** [comment]
Hi. Glad you got it working.
I don't know what you mean by DNG without changes, but the converter accepts a list of files and/or folders as input and converts to the same folder by default . In order for you to have metadata from jpegs that correlate to the raw files embedded in the DNG, it is best to just keep the raw files along with the original jpegs without renaming any of them. Basically running the cli with -h flag will provide usage information.

**Comment by jh96** [comment]
Just to recap for any other people finding it difficult to get their RAW files to convert on a Mac, this is the basic how to: Just don't type the quote marks.

**Change the permission on the script.**
Type "cd" [drag sjcam_raw2dng_v1.0.1_macosx **folder** here]
Type "ls –l"
Hit return.
Then type "chmod 755" [Drag the  sjcam_raw2dng here]
Hit return.
If you type "ls –l" again and hit return you'll see that the file prefix changed from -rw-r--r-- to -rwxr-xr-x meaning the file is owned by you and executable.

**For the file conversion, the terminal the syntax is:**
[Drag sjcam_raw2dng **file** here] [drag image folder here]
and hit return.
Single image conversion is:
[Drag sjcam_raw2dng **file** here] [Drag file for conversion here]
and hit return.

**Comment by jh96** [comment]
Hi Yan,

I couldn't make the -h flag work, but the information was in the files without it.

I started comparing some of the files to see if the EXIF information was being transferred from the jpeg to the DNG - there is info in the DNG, but it's not the same as in the JPEG it took the info from.

<img width="524" alt="screen shot 2016-09-15 at 22 23 05" src="https://cloud.githubusercontent.com/assets/14791142/18568259/47f07c30-7b94-11e6-906e-8dcacc718c9f.png">

Can the differences be explained?

**Comment by yanburman** [comment]
Hi,
The date photo was taken should be the same, but date created is obviously different. Color space is different because this is raw. Resolution is different because sjcam camera software does some cropping and interpolation, while raw contains all data captured by sensor. Focal length reported by sjcam is wrong, so that data is not taken from jpeg. F number seems to be bogus at least for sj5000x as well, so it is also hard coded in the converter. Anyway it seems that sjcam never change aperture, so this info is useless.

**Comment by jh96** [comment]
SJCAM should be paying you to be a developer.
Not only can I now use my M20 for the purpose it was intended for, but you've provided excellent answers!
